### ISSUE TITLE
get list of ARC training tasks with two test inputs for exclusion

### ISSUE THREAD

**Issue by wkvong** [aysjajohnson/ARC#1]
- how many training tasks have two test inputs?
- can we keep a list of these to be excluded from our study?

**Comment by aysjajohnson** [comment]
Also get a list of tasks with three or fewer training examples and those with grid sizes less than 10x10

**Comment by aysjajohnson** [comment]
I did this in the descriptive_stats notebook (lists can be generated there).

There are 14 tasks with two test inputs. 
There are 140 tasks which have three or fewer training examples and are less than or equal to 10x10 in size.
