### ISSUE TITLE
modify grid lines to be white rather than grey

### ISSUE THREAD

**Issue by wkvong** [aysjajohnson/ARC#2]
the grey grid lines make it difficult to click/edit the grey cells, if it's easy it might be worth changing them to another more visible colour like white, see training input grid below:

<img width="881" alt="image" src="https://user-images.githubusercontent.com/433451/79902032-c8057280-83de-11ea-95cf-e3c89f5fb864.png">

**Comment by aysjajohnson** [comment]
The only thing I wonder about is how intentional this was -- maybe there are some grids where this is important? I'll work on changing it for now, it should be pretty easy to revert in either case

**Comment by aysjajohnson** [comment]
![Screen Shot 2020-05-20 at 5 17 24 PM](https://user-images.githubusercontent.com/17600256/82498384-e3d36580-9abd-11ea-9a1c-01b6ab67973d.png)

**Comment by aysjajohnson** [comment]
this is how it now looks ^

**Comment by wkvong** [comment]
looks much better now!
