### ISSUE TITLE
figure out how to save all participant actions

### ISSUE THREAD

**Issue by wkvong** [aysjajohnson/ARC#3]
we'll want sufficient recording of responses to be able to replay each action performed by participants. based on the current interface, here's a first pass on columns that might be needed:
- step: integer describing the sequence of actions taken (1, 2, 3, etc.)
- output grid: current state of the output grid (need to decide on a format to store this)
- current_tool: either edit/select/flood fill (one of these three is always selected)
- current_colour
- output_height/output_width
- select_cells: if user is in select mode, which cells have they selected?
- select_values: what are the values of the selected cells?
- select_location: are the selected cells from the test input or test output?
- clipboard: if the user presses copy, the values of the selected region go here
- action: what action did the user perform? current list of possible actions: click (whose behaviour varies depending on the current tool), select, copy, paste, change colour, resize height, resize width, copy from input, reset, submit

**Comment by aysjajohnson** [comment]
still in progress, and I'm open to suggestions. right now I'm saving a list of dictionaries, each dictionary holds the current state of the grid plus the updated values for the features listed above. Right now it only updates for floodfill, will fill in the rest later. Not sure if it's the best data structure but it does the job

**Comment by wkvong** [comment]
sounds good to me! the main consideration to me is making sure that eventually the data object easily maps onto a database table or data frame for analysis, so we might have to think a bit more about how to store the values in the output grid and the clipboard.

**Comment by aysjajohnson** [comment]
still working on this, not hard to save things but trying to think of the best way to save the information.

**Comment by wkvong** [comment]
sure, let's talk more tomorrow about how you're thinking about this!

**Comment by aysjajohnson** [comment]
what do you have in mind for a step describing what sequence of actions was taken? Is that just an integer that increases by one each time the save function is called?

**Comment by wkvong** [comment]
yep! basically something to keep track of the order of actions a participant takes for a given trial

**Comment by aysjajohnson** [comment]
I think this is basically resolved -- let's take a look together on Thursday
