### ISSUE TITLE
figure out how to save experiment data

### ISSUE THREAD

**Issue by wkvong** [aysjajohnson/ARC#5]
- most recently, I've been using this library to save my data which gets passed to Mechanical Turk directly and can be downloaded when you retrieve the HITs: https://github.com/longouyang/mmturkey, but would not be opposed to setting up a database or something else

**Comment by aysjajohnson** [comment]
if we use psiturk it has a way of handling this (sets up its own database), so I don't think we'd need to use any external libraries

**Comment by wkvong** [comment]
yep, that sounds good! also, is it straight-forward to save each response to the database after each action in psiturk, or is it more common to do so at the end of a task? if possible, I'd prefer the former since that means less chance of losing data

**Comment by aysjajohnson** [comment]
yeah it's possible to save whenever you want!
